# Usa la imagen oficial de Python 3.10.6
FROM python:3.10.6-slim

# Establece el directorio de trabajo
WORKDIR /app

# Copia tu aplicación o script aquí (opcional)
# COPY . /app

# Ejecuta el contenedor con una shell interactiva (opcional)
CMD ["python"]